class InsertSpecialty < ActiveRecord::Migration[5.1]
  def change
    execute("insert into specialties(description, created_at, updated_at) values ('Abdominal Radiology Radiology-Diagnostic', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Addiction Psychiatry Psychiatry', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Adolescent Medicine Pediatrics', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Adult Cardiothoracic Anesthesiology Anesthesiology', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Adult Reconstructive Orthopaedics Orthopaedic Surgery', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Advanced Heart Failure & Transplant Cardiology Internal Medicine', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Allergy & Immunology', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Anesthesiology', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Biochemical Genetics Medical Genetics', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Blood Banking - Transfusion Medicine Pathology-Anatomic & Clinical', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Cardiothoracic Radiology Radiology-Diagnostic', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Cardiovascular Disease Internal Medicine', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Chemical Pathology Pathology-Anatomic & Clinical', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Child & Adolescent Psychiatry Psychiatry', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Child Abuse Pediatrics Pediatrics', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Child Neurology Neurology', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Clinical & Laboratory Immunology Allergy & Immunology', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Clinical Cardiac Electrophysiology Internal Medicine', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Clinical Neurophysiology Neurology', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Colon & Rectal Surgery', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Congenital Cardiac Surgery Thoracic Surgery', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Craniofacial Surgery Plastic Surgery', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Critical Care Medicine Anesthesiology', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Critical Care Medicine Internal Medicine', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Cytopathology Pathology-Anatomic & Clinical', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Dermatology', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Dermatopathology Dermatology', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Developmental-Behavioral Pediatrics Pediatrics', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Emergency Medicine', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Endocrinology, Diabetes & Metabolism Internal Medicine', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Endovascular Surgical Neuroradiology Neurological Surgery', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Endovascular Surgical Neuroradiology Neurology', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Endovascular Surgical Neuroradiology Radiology-Diagnostic', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Family Medicine', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Family Practice', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Female Pelvic Medicine & Reconstructive Surgery Obstetrics & Gynecology', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Foot & Ankle Orthopaedics Orthopaedic Surgery', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Forensic Pathology Pathology-Anatomic & Clinical', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Forensic Psychiatry Psychiatry', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Gastroenterology Internal Medicine', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Geriatric Medicine Family Medicine', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Geriatric Medicine Family Practice', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Geriatric Medicine Internal Medicine', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Geriatric Psychiatry Psychiatry', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Hand Surgery Orthopaedic Surgery', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Hand Surgery Plastic Surgery', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Hand Surgery Surgery-General', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Hematology & Oncology Internal Medicine', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Hematology Internal Medicine', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Hematology Pathology-Anatomic & Clinical', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Infectious Disease Internal Medicine', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Internal Medicine', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Internal Medicine-Pediatrics', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Interventional Cardiology Internal Medicine', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Medical Genetics', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Medical Microbiology Pathology-Anatomic & Clinical', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Medical Toxicology Emergency Medicine', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Medical Toxicology Preventive Medicine', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Molecular Genetic Pathology Medical Genetics', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Muscoskeletal Radiology Radiology-Diagnostic', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Musculoskeletal Oncology Orthopaedic Surgery', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Neonatal-Perinatal Medicine Pediatrics', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Nephrology Internal Medicine', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Neurological Surgery', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Neurology', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Neuromuscular Medicine Neurology', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Neuromuscular Medicine Physical Medicine & Rehabilitation', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Neuropathology Pathology-Anatomic & Clinical', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Neuroradiology Radiology-Diagnostic', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Nuclear Medicine', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Nuclear Radiology Radiology-Diagnostic', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Obstetric Anesthesiology Anesthesiology', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Obstetrics & Gynecology', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Oncology Internal Medicine', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Ophthalmic Plastic & Reconstructive Surgery Ophthalmology', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Ophthalmology', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Orthopaedic Sports Medicine Orthopaedic Surgery', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Orthopaedic Surgery', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Orthopaedic Surgery of the Spine Orthopaedic Surgery', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Orthopaedic Trauma Orthopaedic Surgery', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Otolaryngology', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Otology - Neurotology Otolaryngology', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Pain Medicine Anesthesiology', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Pain Medicine Neurology', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Pain Medicine Physical Medicine & Rehabilitation', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Pathology-Anatomic & Clinical', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Pediatric Anesthesiology Anesthesiology', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Pediatric Cardiology Pediatrics', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Pediatric Critical Care Medicine Pediatrics', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Pediatric Emergency Medicine Emergency Medicine', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Pediatric Emergency Medicine Pediatrics', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Pediatric Endocrinology Pediatrics', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Pediatric Gastroenterology Pediatrics', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Pediatric Hematology-Oncology Pediatrics', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Pediatric Infectious Diseases Pediatrics', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Pediatric Nephrology Pediatrics', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Pediatric Orthopaedics Orthopaedic Surgery', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Pediatric Otolaryngology Otolaryngology', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Pediatric Pathology Pathology-Anatomic & Clinical', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Pediatric Pulmonology Pediatrics', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Pediatric Radiology Radiology-Diagnostic', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Pediatric Rheumatology Pediatrics', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Pediatric Sports Medicine Pediatrics', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Pediatric Surgery Surgery-General', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Pediatric Transplant Hepatology Pediatrics', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Pediatric Urology Urology', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Pediatrics', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Physical Medicine & Rehabilitation', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Plastic Surgery', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Preventive Medicine', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Procedural Dermatology Dermatology', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Psychiatry', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Pulmonary Disease & Critical Care Medicine Internal Medicine', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Pulmonary Disease Internal Medicine', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Radiation Oncology', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Radiology-Diagnostic', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Rheumatology Internal Medicine', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Sleep Medicine', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Spinal Cord Injury Medicine Physical Medicine & Rehabilitation', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Sports Medicine Emergency Medicine', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Sports Medicine Family Medicine', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Sports Medicine Internal Medicine', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Sports Medicine Physical Medicine & Rehabilitation', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Surgery-General', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Surgical Critical Care Surgery-General', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Thoracic Surgery', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Thoracic Surgery-Integrated Thoracic Surgery', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Transplant Hepatology Internal Medicine', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Urology', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Vascular & Interventional Radiology Radiology-Diagnostic', current_timestamp, current_timestamp);")
    execute("insert into specialties(description, created_at, updated_at) values ('Vascular Surgery Surgery-General', current_timestamp, current_timestamp);")
  end
end
